// Mocks generated by Mockito 5.4.6 from annotations
// in app4_receitas/test/ui/Auth/auth_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:app4_receitas/data/models/user_profile.dart' as _i7;
import 'package:app4_receitas/data/repositories/auth_repository.dart' as _i3;
import 'package:app4_receitas/data/services/auth_service.dart' as _i11;
import 'package:app4_receitas/utils/app_error.dart' as _i6;
import 'package:either_dart/either.dart' as _i5;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:supabase_flutter/supabase_flutter.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue:
                _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>>.value(
                  _i8.dummyValue<_i5.Either<_i6.AppError, _i7.UserProfile>>(
                    this,
                    Invocation.getter(#currentUser),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>>);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>> signInWithPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>>.value(
                  _i8.dummyValue<_i5.Either<_i6.AppError, _i7.UserProfile>>(
                    this,
                    Invocation.method(#signInWithPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>>);

  @override
  _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>> signUp({
    required String? email,
    required String? password,
    required String? username,
    required String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #username: username,
              #avatarUrl: avatarUrl,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>>.value(
                  _i8.dummyValue<_i5.Either<_i6.AppError, _i7.UserProfile>>(
                    this,
                    Invocation.method(#signUp, [], {
                      #email: email,
                      #password: password,
                      #username: username,
                      #avatarUrl: avatarUrl,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, _i7.UserProfile>>);

  @override
  _i4.Future<_i5.Either<_i6.AppError, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i5.Either<_i6.AppError, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.AppError, void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, void>>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListener(_i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i9.Disposer);

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i10.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListenerId(Object? key, _i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i9.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i11.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i12.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i12.AuthState>.empty(),
          )
          as _i4.Stream<_i12.AuthState>);

  @override
  _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>> signInWithPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>>.value(
                  _i8.dummyValue<_i5.Either<_i6.AppError, _i12.AuthResponse>>(
                    this,
                    Invocation.method(#signInWithPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>>);

  @override
  _i4.Future<_i5.Either<_i6.AppError, Map<String, dynamic>?>> fetchUserProfile(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [userId]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.AppError, Map<String, dynamic>?>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.AppError, Map<String, dynamic>?>
                  >(this, Invocation.method(#fetchUserProfile, [userId])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>> signUp({
    required String? email,
    required String? password,
    required String? username,
    required String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #username: username,
              #avatarUrl: avatarUrl,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>>.value(
                  _i8.dummyValue<_i5.Either<_i6.AppError, _i12.AuthResponse>>(
                    this,
                    Invocation.method(#signUp, [], {
                      #email: email,
                      #password: password,
                      #username: username,
                      #avatarUrl: avatarUrl,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>>);

  @override
  _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>> insertUser({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>>.value(
                  _i8.dummyValue<_i5.Either<_i6.AppError, _i12.AuthResponse>>(
                    this,
                    Invocation.method(#insertUser, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, _i12.AuthResponse>>);

  @override
  _i4.Future<_i5.Either<_i6.AppError, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i5.Either<_i6.AppError, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.AppError, void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.AppError, void>>);
}
